In [1]:
!pip install -q datasets

In [2]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from huggingface_hub import login
from transformers import pipeline
from datasets import load_dataset
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score
from torch.utils.data import Dataset
import torch.nn.functional as F
import torch

In [3]:
# Log in with your token (Replace with your actual Hugging Face token)
token = "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"  # Replace with your token
login(token=token, add_to_git_credential=True)

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
fiqa_ds = load_dataset("TheFinAI/fiqa-sentiment-classification")
fiqa_df = {k: pd.DataFrame(v) for k, v in fiqa_ds.items()}

sft_df = {}
for key in ['train', 'val', 'test']:
    sft_df[key] = pd.read_csv(f'/content/drive/My Drive/my_dataset/sft/{key}.csv')

finsen_df = pd.read_csv('/content/drive/My Drive/my_dataset/finsen_infer.csv')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [6]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    finsen_df,
    test_size=0.1,
    shuffle=True
)

val_df

,Title,Tag,Time,Content,title_label,pos_logit,neg_logit,neu_logit,psudo_label
5132,Anthem earnings at 6.79 USD,Earnings,20/10/2021,Anthem earnings at 6.79 USDUnited StatesÂ Earn...,neu,40.250,26.1250,25.375,positive
3622,Principal Financial earnings above expectation...,Earnings,28/04/2022,Principal Financial earnings above expectation...,pos,43.000,24.7500,25.875,positive
3111,US Futures Climb as Risk Appetite Returns,Stock Market,20/06/2022,US Futures Climb as Risk Appetite ReturnsUnite...,pos,34.750,27.1250,33.750,positive
12603,Dollar Continues To Strengthen,Currency,28/12/2016,Dollar Continues To Strengthen United StatesÂ ...,neu,41.750,27.8750,30.125,positive
9784,US Stocks Rally on Friday,Stock Market,4/01/2019,US Stocks Rally on FridayUnited StatesÂ Stock ...,pos,36.250,20.0000,25.125,positive
...,...,...,...,...,...,...,...,...,...
8321,Dollar Falls for 2nd Day,Currency,8/05/2020,Dollar Falls for 2nd DayUnited StatesÂ Currenc...,neg,44.750,29.8750,39.000,positive
831,Visa Hits 6-week High,stocks,3/04/2023,Visa Hits 6-week HighUnited StatesÂ stocksVisa...,pos,36.000,21.8750,24.000,positive
891,Wall Street Starts Week Higher on Banks Relief,Stock Market,27/03/2023,Wall Street Starts Week Higher on Banks Relief...,pos,27.500,15.0625,21.625,positive
12988,US New Home Sales Fall Less than Expected,New Home Sales,26/09/2016,US New Home Sales Fall Less than ExpectedUnite...,pos,24.875,27.0000,31.250,neutral
8810,US Stocks Close Higher,Stock Market,10/02/2020,US Stocks Close Higher United StatesÂ Stock Ma...,pos,32.500,20.5000,26.625,positive

In [7]:
workdir = '/content/drive/My Drive/my_ckpt/distill'

In [8]:
pipe = pipeline("text-classification", model="ProsusAI/finbert", top_k=None)
pipe(sft_df['val']['sentence'][0], truncation=True)

Device set to use cuda:0

[[{'label': 'positive', 'score': 0.9398723840713501},
  {'label': 'negative', 'score': 0.039553407579660416},
  {'label': 'neutral', 'score': 0.02057422325015068}]]

In [9]:
preds = [
    out[0]["label"]
    for out in pipe(val_df["Content"].tolist())
]
accuracy_score(val_df["psudo_label"].tolist(), preds)

0.5736842105263158

In [10]:
class DistillDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=512):
        self.sentences = df["Content"].tolist()
        self.teacher_logits = df[["pos_logit", "neg_logit", "neu_logit"]].values.tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.sentences[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["teacher_logits"] = torch.tensor(self.teacher_logits[idx])
        return item

In [11]:
class DistillTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        if "teacher_logits" not in inputs:
            return super().compute_loss(model, inputs, return_outputs, **kwargs)
        teacher_logits = inputs.pop("teacher_logits")
        outputs = model(**inputs)
        student_logits = outputs.logits
        T = 2.0
        teacher_probs = F.softmax(teacher_logits / T, dim=-1)
        student_log_probs = F.log_softmax(student_logits / T, dim=-1)
        loss = F.kl_div(student_log_probs, teacher_probs, reduction="batchmean") * T * T
        return (loss, outputs) if return_outputs else loss

In [12]:
class EvalDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=256):
        self.sentences = df["Content"].tolist()
        self.labels    = df["psudo_label"].map({
                            "positive": 0,
                            "negative": 1,
                            "neutral":  2
                        }).tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.sentences[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

In [13]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, preds)}

In [14]:
training_args = TrainingArguments(
    output_dir=workdir,
    per_device_train_batch_size=32,
    num_train_epochs=3,
    learning_rate=2e-5,
    remove_unused_columns=False,

    logging_strategy="steps",
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
)

dataset = DistillDataset(train_df, pipe.tokenizer)
eval_dataset = EvalDataset(val_df, pipe.tokenizer)

trainer = DistillTrainer(
    model=pipe.model,
    args=training_args,
    train_dataset=dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Currently logged in as: xw3037 (xw3037-columbia-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=1284, training_loss=0.7423957166642043, metrics={'train_runtime': 844.9534, 'train_samples_per_second': 48.571, 'train_steps_per_second': 1.52, 'total_flos': 1.079817466355712e+16, 'train_loss': 0.7423957166642043, 'epoch': 3.0})

In [15]:
preds = [
    out[0]["label"]
    for out in pipe(val_df["Content"].tolist())
]
accuracy_score(val_df["psudo_label"].tolist(), preds)

0.9

In [17]:
# preds = [
#     out[0]["label"]
#     for out in pipe(sft_df['val']["sentence"].tolist())
# ]
# accuracy_score(sft_df['val']["label"].tolist(), preds)

0.8247422680412371

In [16]:
# tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
# model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
# nlp = pipeline(
#     "sentiment-analysis",
#     model=model,
#     tokenizer=tokenizer,
#     return_all_scores=True,
# )
# sentence = prompt_template.format(text=sft_df['val']['sentence'][2])
# nlp(sentence)